module.exports = {
    ApplicationError: require("./ApplicationError"),
    ValidationError: require("./ValidationError"),
    ForbiddenError: require("./ForbiddenError"),
    UnauthorizedError: require("./UnauthorizedError"),
    NotFoundError: require("./NotFoundError"),
    BadRequestError: require("./BadRequestError"),
    ConflictError: require("./ConflictError"),
    PayloadTooLargeError: require("./PayloadTooLargeError"),
    PolicyError: require("./PolicyError"),
    TooManyRequestsError: require("./TooManyRequestsError"),
    BaseError: require("./BaseError"),
    DatabaseError: require("./DatabaseError"),
    ExternalServiceError: require("./ExternalServiceError"),
};
